server:
  port: 30080

management:
  security:
    enabled: false

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: svca-service
          uri: lb://svca-service
          predicates:
            - Path=/svca/**
          filters:
            - StripPrefix=0
        - id: svcb-service
          uri: lb://svcb-service
          predicates:
            - Path=/svcb/**
          filters:
            - StripPrefix=0
        - id: openapi
          uri: http://localhost:${server.port}
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000

ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
springdoc:
  swagger-ui:
    urls:
      - name: gateway
        url: /v3/api-docs
      - name: svca
        url: /v3/api-docs/svca
      - name: svcb
        url: /v3/api-docs/svcb
