apiVersion: apps/v1
kind: Deployment
metadata:
  name: svca-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: svca-service
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: svca-service
    spec:
      initContainers:
        - name: init-skywalking-agent
          image: apache/skywalking-java-agent:8.12.0-java8
          command:
            - 'sh'
            - '-c'
            - 'set -ex;mkdir -p /vmskywalking/agent;cp -r /skywalking/agent/* /vmskywalking/agent;'
          volumeMounts:
            - mountPath: /vmskywalking/agent
              name: skywalking-agent
      containers:
        - image: haiyanggroup-docker.pkg.coding.net/spring-boot-cloud/svca-service/svca-service:master-202209111700
          imagePullPolicy: Always
          name: svca-service
          ports:
            - containerPort: 30880
              protocol: TCP
          volumeMounts:
            - mountPath: /opt/skywalking/agent
              name: skywalking-agent
          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", "sleep 36"]
      volumes:
        - name: skywalking-agent
          emptyDir: { }
---
apiVersion: v1
kind: Service
metadata:
  name: svca-service
spec:
  type: NodePort
  ports:
    - name: http
      port: 30880
      protocol: TCP
      nodePort: 30880
      targetPort: 30880
  selector:
    app: svca-service