apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: gateway
    spec:
      initContainers:
        - name: init-skywalking-agent
          image: apache/skywalking-java-agent:8.12.0-java8
          command:
            - 'sh'
            - '-c'
            - 'set -ex;mkdir -p /vmskywalking/agent;cp -r /skywalking/agent/* /vmskywalking/agent;'
          volumeMounts:
            - mountPath: /vmskywalking/agent
              name: skywalking-agent
      containers:
        - image: haiyanggroup-docker.pkg.coding.net/spring-boot-cloud/gateway/gateway:master-202209111656
          imagePullPolicy: Always
          name: gateway
          ports:
            - containerPort: 30080
              protocol: TCP
          env:
            - name: SKYWALKING_ADDR
              value: skywalking-oap-server
            - name: APP_ID
              value: gateway
          volumeMounts:
            - mountPath: /opt/skywalking/agent
              name: skywalking-agent
      volumes:
        - name: skywalking-agent
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  type: NodePort
  ports:
    - name: http
      port: 30080
      protocol: TCP
      targetPort: 30080
      nodePort: 30080
  selector:
    app: gateway