apiVersion: apps/v1
kind: Deployment
metadata:
  name: config
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: config
    spec:
      initContainers:
        - name: init-skywalking-agent
          image: apache/skywalking-java-agent:8.12.0-java8
          command:
            - 'sh'
            - '-c'
            - 'set -ex;mkdir -p /vmskywalking/agent;cp -r /skywalking/agent/* /vmskywalking/agent;'
          volumeMounts:
            - mountPath: /vmskywalking/agent
              name: skywalking-agent
      containers:
        - image: haiyanggroup-docker.pkg.coding.net/spring-boot-cloud/config/config:master-202209111517
          imagePullPolicy: Always
          name: config
          ports:
            - containerPort: 8888
              protocol: TCP
          volumeMounts:
            - mountPath: /opt/skywalking/agent
              name: skywalking-agent
      volumes:
        - name: skywalking-agent
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: config
spec:
  type: NodePort
  ports:
    - name: http
      port: 30876
      protocol: TCP
      targetPort: 30876
      nodePort: 31018
  selector:
    app: config